// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfmrungspmrtqsvhxtga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmbXJ1bmdzcG1ydHFzdmh4dGdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDc0NDksImV4cCI6MjA2OTcyMzQ0OX0.n5WfHKxvtDYVrFCFF-DwI2OA7tPrR1byrNLUK7UeEn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});